// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAbout() {
  return window['go']['main']['App']['GetAbout']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsPortable() {
  return window['go']['main']['App']['IsPortable']();
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ResetAdmin() {
  return window['go']['main']['App']['ResetAdmin']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetAutoStartService(arg1) {
  return window['go']['main']['App']['SetAutoStartService'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TrayAbout() {
  return window['go']['main']['App']['TrayAbout']();
}

export function TrayHideWindow() {
  return window['go']['main']['App']['TrayHideWindow']();
}

export function TrayIsAutoStart() {
  return window['go']['main']['App']['TrayIsAutoStart']();
}

export function TrayOpenBrowser() {
  return window['go']['main']['App']['TrayOpenBrowser']();
}

export function TrayOpenDataDir() {
  return window['go']['main']['App']['TrayOpenDataDir']();
}

export function TrayOpenLogsWindow() {
  return window['go']['main']['App']['TrayOpenLogsWindow']();
}

export function TrayQuit() {
  return window['go']['main']['App']['TrayQuit']();
}

export function TrayRestart() {
  return window['go']['main']['App']['TrayRestart']();
}

export function TrayShowWindow() {
  return window['go']['main']['App']['TrayShowWindow']();
}

export function TrayStart() {
  return window['go']['main']['App']['TrayStart']();
}

export function TrayState() {
  return window['go']['main']['App']['TrayState']();
}

export function TrayStop() {
  return window['go']['main']['App']['TrayStop']();
}

export function TrayToggleAutoStart() {
  return window['go']['main']['App']['TrayToggleAutoStart']();
}
