// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {alist} from '../models';

export function GetAbout():Promise<Record<string, string>>;

export function GetLogs():Promise<Array<alist.LogLine>>;

export function GetState():Promise<alist.State>;

export function HideWindow():Promise<void>;

export function IsPortable():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function OpenBrowser():Promise<void>;

export function OpenDataDir():Promise<void>;

export function QuitApp():Promise<void>;

export function ResetAdmin():Promise<void>;

export function Restart():Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetAutoStartService(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function TrayAbout():Promise<void>;

export function TrayHideWindow():Promise<void>;

export function TrayIsAutoStart():Promise<boolean>;

export function TrayOpenBrowser():Promise<void>;

export function TrayOpenDataDir():Promise<void>;

export function TrayOpenLogsWindow():Promise<void>;

export function TrayQuit():Promise<void>;

export function TrayRestart():Promise<void>;

export function TrayShowWindow():Promise<void>;

export function TrayStart():Promise<void>;

export function TrayState():Promise<string>;

export function TrayStop():Promise<void>;

export function TrayToggleAutoStart():Promise<boolean>;
